name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: corepack enable
      - run: pnpm i
      - run: pnpm lint-check
      - run: pnpm tsc
      - run: pnpm build
      - run: pnpm test
      - run: pnpm dev-isort-fix
      - run: pnpm dev-isort-prettier
